// Command agenthostcatalog renders the public agent-host support matrix from
// the same typed catalog used by the CLI and onboarding.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/nkiyohara/corresync/internal/agenthost"
)

const defaultOutput = "docs/generated/agent-hosts.md"

func main() {
	check := flag.Bool("check", false, "fail when the checked-in matrix is stale")
	output := flag.String("output", defaultOutput, "generated Markdown path")
	flag.Parse()

	content := render(agenthost.DefaultCatalog())
	if *check {
		existing, err := os.ReadFile(*output) // #nosec G304 -- explicit developer-controlled output path.
		if err != nil {
			fail(fmt.Errorf("read generated agent-host catalog: %w", err))
		}
		if !bytes.Equal(existing, content) {
			fail(errors.New("checked-in agent-host catalog is stale; run task integrations:generate"))
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(*output), 0o750); err != nil {
		fail(fmt.Errorf("create generated documentation directory: %w", err))
	}
	if err := os.WriteFile(*output, content, 0o644); err != nil { // #nosec G306 -- public generated documentation.
		fail(fmt.Errorf("write generated agent-host catalog: %w", err))
	}
}

func render(catalog agenthost.Catalog) []byte {
	var document strings.Builder
	document.WriteString(`# Agent-host catalog

<!-- Generated by tools/agenthostcatalog; do not edit by hand. -->
<!-- markdownlint-disable MD013 -->
| Host | Stable ID and aliases | Surfaces | Support | Local stdio MCP | Agent Skill | Native format | MCPB | Marketplace surface | Published | Current lifecycle |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
`)
	for _, host := range catalog.Hosts() {
		aliases := "—"
		if len(host.Aliases) > 0 {
			aliases = strings.Join(host.Aliases, ", ")
		}
		native := "—"
		if host.Capabilities.NativePackage != "" {
			native = string(host.Capabilities.NativePackage)
		}
		_, _ = fmt.Fprintf(
			&document,
			"| [%s](%s) | `%s` (%s) | %s | `%s` | %s | %s | %s | %s | %s | %s | %s |\n",
			host.DisplayName,
			host.DocumentationURL,
			host.ID,
			aliases,
			joinSurfaces(host.Surfaces),
			host.Support,
			yesNo(host.Capabilities.LocalStdioMCP),
			yesNo(host.Capabilities.AgentSkill),
			native,
			yesNo(host.Capabilities.SelfContainedMCPB),
			yesNo(host.Capabilities.MarketplaceSurface),
			yesNo(host.Capabilities.Published),
			lifecycleSummary(host.Lifecycle),
		)
	}
	document.WriteString("<!-- markdownlint-enable MD013 -->\n")
	return []byte(document.String())
}

func joinSurfaces(surfaces []agenthost.Surface) string {
	values := make([]string, len(surfaces))
	for index := range surfaces {
		values[index] = string(surfaces[index])
	}
	return strings.Join(values, ", ")
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "—"
}

func lifecycleSummary(lifecycle agenthost.Lifecycle) string {
	if lifecycle.Setup {
		return "setup + inspect + verify + repair + remove"
	}
	if lifecycle.AdapterID != "" {
		return "planned adapter"
	}
	return "detect only"
}

func fail(err error) {
	_, _ = fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
